const OK = 200;
const CREATED = 201;
const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const SERVER_ERROR = 500;
const UNAUTHORIZED = 401;
const CONFLICT = 409;
const METHOD_NOT_ALLOWED = 405;

module.exports = {
  OK, CREATED, BAD_REQUEST, NOT_FOUND, SERVER_ERROR, UNAUTHORIZED, CONFLICT, METHOD_NOT_ALLOWED,
};
